name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:
    inputs:
      buildFlags:
        required: false
        type: string

jobs:

  buildLinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp --quiet
          haxelib install hxpkg --global
          haxelib run hxpkg setup --global
          hxpkg install
          haxelib list

      - name: Compile
        run: haxelib run lime build Project.xml linux -D ${{ inputs.buildFlags }}

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: linuxBuild
          path: export/release/linux/bin


  buildWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.0

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install Haxelib
        run: |
          haxelib setup C:\Users\runneradmin\haxelib
          haxelib install hxcpp --quiet
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib list
        shell: cmd

      - name: Compile
        run: haxelib run lime build windows -D ${{ inputs.buildFlags }}

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: windowsBuild
          path: export/release/windows/bin


  buildMacIntel:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.0

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp --quiet
          haxelib install hxpkg --global
          haxelib run hxpkg setup --global
          hxpkg install

      - name: Compile
        run: haxelib run lime build mac -64 -D ${{ inputs.buildFlags }}

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: macBuild-intel
          path: export/release/macos/bin


  buildMacArm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.0

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp --quiet
          haxelib install hxpkg --global
          haxelib run hxpkg setup --global
          hxpkg install

      - name: Compile
        run: haxelib run lime build mac -arm64 -D ${{ inputs.buildFlags }}

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: macBuild-arm
          path: export/release/macos/bin


  buildAndroid:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp --quiet
          haxelib install lime --quiet
          haxelib install openfl --quiet

      - name: Install Android SDK + NDK
        uses: android-actions/setup-android@v3

      - name: Build Android
        run: haxelib run lime build android -release -Dlegacy

      - name: Upload Android Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk


  buildIOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.0

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp --quiet
          haxelib install lime --quiet
          haxelib install openfl --quiet

      - name: Build iOS
        run: haxelib run lime build ios -nosign -release

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@main
        with:
          name: iOSBuild
          path: export/release/ios/build/Release-iphoneos/*.ipa
