name: Main

on:
  push:
    branches: [ main, experimental ]
  pull_request:
    branches: [ main, experimental ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Windows
            os: windows-2022
            buildArgs: windows
            setupCommand: ".\\setup\\windows.bat"
            artifactName: windowsBuild-x86_64
            artifactPath: export/release/windows/bin/*

          - name: Linux
            os: ubuntu-22.04
            buildArgs: linux
            setupCommand: sh ./setup/unix.sh
            artifactName: linuxBuild-x86_64
            artifactPath: export/release/linux/bin/*

          - name: macOS x86_64
            os: macos-15
            buildArgs: "mac -64 -D HXCPP_M64"
            setupCommand: sh ./setup/unix.sh
            artifactName: macOSBuild-x86_64
            artifactPath: export/release/macos/bin/*

          - name: macOS ARM64
            os: macos-15
            buildArgs: "mac -arm64 -D HXCPP_ARM64"
            setupCommand: sh ./setup/unix.sh
            artifactName: macOSBuild-arm64
            artifactPath: export/release/macos/bin/*

          - name: iOS
            os: macos-15
            buildArgs: "ios -nosign"
            setupCommand: sh ./setup/unix.sh
            artifactName: iOSBuild
            artifactPath: export/release/ios/build/Release-iphoneos/*.ipa

    uses: ./.github/workflows/build.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      setupCommand: ${{ matrix.setupCommand }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release Tag
        id: tag
        run: |
          VERSION="v$(date +'%Y.%m.%d.%H%M')"
          echo "tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: "Automated Build ${{ steps.tag.outputs.tag }}"
          body: |
            Automated multi‑platform build.
            Generated from commit: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: ./artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
